import React from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>X-CLONE</title>
      </head>
      <body className="dark">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
